import Head from 'next/head';
import { Col, Row } from 'antd';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

import useAuth from '../hooks/useAuth';

export default function Home() {
  const router = useRouter();
  const { fetchProfile } = useAuth();
  const [fetching, setFetching] = useState(true);

  useEffect(() => {
    (async function () {
      const res = await fetchProfile('shipon2285a@gmail.com', setFetching);
      if (!res?.createdAt) router.push('/login');
    })();
  }, [fetchProfile, router]);

  if (fetching) return <p>Loading...</p>;

  return (
    <div>
      <Head>
        <title>Bookmark App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row>
        <Col span={12} offset={6}>
          <h1 style={{ textAlign: 'center' }}>Welcome to the bookmark app</h1>
        </Col>
      </Row>
    </div>
  );
}
